# Generated by Django 5.1.1 on 2024-09-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practic4', '0002_student_teacher_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to='book/%Y/%m/%d'),
        ),
    ]
